language: ruby
rvm:
  - head
  - head-clang
  - 2.6.1
  - 2.6.0
  - 2.6.0-rc2
  - 2.6.0-rc1
  - 2.6.0-preview3
  - 2.6.0-preview2
  - 2.6.0-preview1
  - 2.5.3
  - 2.5.2
  - 2.5.1
  - 2.5.0
  - 2.5.0-preview1
  - 2.4.5
  - 2.4.4
  - 2.4.3
  - 2.4.2
  - 2.4.1
  - 2.4.1-clang
  - 2.4.0
  - 2.4.0-rc1
  - 2.4.0-preview3
  - 2.4.0-preview3-clang
  - 2.4.0-preview2
  - 2.4.0-preview2-clang
  - 2.4.0-preview1
  - 2.4.0-preview1-clang
  - 2.3.8
  - 2.3.7
  - 2.3.6
  - 2.3.5
  - 2.3.4
  - 2.3.4-clang
  - 2.3.3
  - 2.3.2
  - 2.3.1
  - 2.3.1-clang
  - 2.3.0
  - 2.3.0-preview2
  - 2.3.0-preview2-clang
  - 2.3.0-preview1
  - 2.3.0-preview1-clang
  - 2.3.0-clang
  - 2.2.10
  - 2.2.9
  - 2.2.8
  - 2.2.7
  - 2.2.7-clang
  - 2.2.6
  - 2.2.5
  - 2.2.4
  - 2.2.4-clang
  - 2.2.3
  - 2.2.3-clang
  - 2.2.2
  - 2.2.2-clang
  - 2.2.1
  - 2.1.10
  - 2.1.10-clang
  - 2.1.9
  - 2.1.9-clang
  - 2.1.8
  - 2.1.8-clang
  - 2.1.7
  - 2.1.7-clang
  - 2.1.6
  - 2.1.5
  - 2.1.4
  - 2.1.3
  - 2.1.2
  - 2.1.0
  - 2.0.0-p648
  - 2.0.0-p648-clang
  - 2.0.0-p647
  - 2.0.0-p647-clang
  - 2.0.0-p645
  - 1.9.3-p551
  - 1.9.2-p330
  - 1.8.7
  - 1.8.7-p371
  - 1.8.7-head

before_install:
# - bundle install --gemfile=.travis.gemfile
# - bundle lock --lockfile=.travis.gemfile.lock --add-platform ruby
# - bundle lock --lockfile=.travis.gemfile.lock --add-platform x86_64-linux

install:
  # Bundler downgrade should be removed when the issue is fixed upstream
  #gem uninstall bundler -x
  #gem install bundler -v ">1.1.4"

bundler_args: --without production

before_script:
 - chmod +x ./script/cibuild # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/cibuild

gemfile:
 #- Gemfile
 - gemfiles/travis.gemfile

# branch whitelist, only for GitHub Pages
#branches:
#  only:
#  - gh-pages     # test the gh-pages branch
#  - /pages-(.*)/ # test every branch which starts with "pages-"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
