title: Cameron Trow
description: >
  My Corner of the Internet
baseurl: ""
url: "http://tumble1999.github.io"
repository: tumble1999/tumble1999.github.io

logo: /favicon.gif

permalink: pretty
production: true
safe: true

plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown
theme: minima

kramdown:
  input: GFM
  auto_ids: false

excludes:
  - _config.yml
  - .gitignore
  - .git
  - .parcel-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - parcel
  - yarn-error.log
  - gemfiles
  - parcel.js


collections:
  projects:
    output: true
  engine:
    output: true
  platforms:
    output: true
  jobs:
    output: true
  education:
    output: true
  languages:
    output: true
  root:
    output: true
  lists:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: item
      header: true
  - scope:
      path: ""
      type: root
    values:
      layout: item
      permalink: /:title
      header: false
  - scope:
      path: ""
      type: lists
    values:
      layout: item
      permalink: /:title
      header: false
