# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create7 any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tumble
description: > # this means to ignore newlines until "baseurl:"
  My Github Website
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tumble1999.github.io" # the base hostname & protocol for your site, e.g. http://example.com

logo: /favicon.gif

social:
  name: Cameron Trow
  links:
    - https://twitter.com/camerontrow
    - https://www.facebook.com/TumbleGamer
    - https://www.linkedin.com/in/CameronTrow
    - https://plus.google.com/+BenBalter
    - https://github.com/tumble1999

webmaster_verifications:
  google: 1234
  bing: 1234
  alexa: 1234
  yandex: 1234

permalink: pretty
production: true

collections:
 github:
  output: true
 portfolio:
  output: true
 unity:

gems:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
   - jekyll-seo-tag
   
   
   
defaults:
  - scope:
      path: ""
    values:
      image: /favicon.gif
  - scope:
        path: ""
        type: pages
    values:
        categories: []
        author: ""
  - scope:
        path: ""
        type: posts
    values:
        categories: []
        tags: []
        author: ""
        excerpt: >
        image:
  - scope:
        path: ""
        type: github
    values:
        user: 
        repo: 

# Build settings
markdown: kramdown
# theme: minima
excludes:
  - lib
  - Gemfile
  - Gemfile.lock
  - node_modules
  - bower.json
  - "*.sh"
  - README.md
  - gulffile.js
  - package.json
  - vendor
  
  
# STATICMAN
staticman:
  allowedFields: ["name", "message", "email", "url", "reply"]
  branch: master
  commitMessage: "New Comment"
  generatedFields:
    date:
      type: date
      options:
        format: "timestamp-seconds"
  moderation: false
  filename: "entry{@timestamp}"
  format: yml
  path: "_data/comments"
  requiredFields: ["name", "message", "url"]
